on:
    push:
        branches:
            - main
            - release/x.x

name: Make Release Candidate

jobs:
    release-please-rc:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - uses: googleapis/release-please-action@v4
              with:
                  config-file: .github/release-please/config.json
                  manifest-file: .github/release-please/manifest.json
